### ISSUE TITLE
HACKTOBERFEST 2020

### ISSUE THREAD

**Issue by avats-dev** [BitByte-TPC/first-bit#35]
# Hacktoberfest 2020 

<p align="center">
    <a href="https://hacktoberfest.digitalocean.com/">
        <img src="https://github.com/BitByte-TPC/first-bit/blob/master/assets/HF/logo.svg" width="30%">
    </a>
</p>

<h1 align="center"> Hacktoberfest 2020 🎉</h1>

### As per the ethics of [first-bit](https://github.com/BitByte-TPC/first-bit), you have to abide by just one RULE:
- **This project is for contributors who have never contributed before or are still starting out in Open Source. This project is committed to help first timers get started** *(not for people finding ways to complete their 4 PRs as formality)*, **and people contributing should respect this commitment while they're here. Thanks.**

📢 *Register [here](https://hacktoberfest.digitalocean.com) for Hacktoberfest.*
 
</br>

---

### GOAL
To help you contribute to OPEN SOURCE REALM.

### WHAT YOU NEED TO DO
- Go and open **[README](https://github.com/BitByte-TPC/first-bit/blob/master/README.md)**.
- Follow the steps there :rocket: :tada:.

</br>

---

![Hacktoberfest2020](https://raw.githubusercontent.com/adityaarakeri/super-scripts/master/hacktoberfest2020.png)

---

**Comment by avats-dev** [comment]
> # Hacktoberfest 2020
> 
> [ <img alt="" width="30%" src="https://github.com/BitByte-TPC/first-bit/blob/master/assets/HF/logo.svg"> ](https://hacktoberfest.digitalocean.com/)
> # Hacktoberfest 2020 tada
> #### So, the festive season for OPEN SOURCE is back guys and we are here to help you contribute (and grab the swags tada ).
> ### speaking_head Hacktoberfest encourages participation in the open source community, which grows bigger every year. Complete the 2020 challenge and earn a limited edition T-shirt.
> 
> loudspeaker **Register [here](https://hacktoberfest.digitalocean.com) for Hacktoberfest and make four pull requests (PRs) between October 1st-31st to grab free SWAGS fire.**
> 
> ### GOAL
> 
> To help you contribute to OPEN SOURCE REALM.
> ### WHAT YOU NEED TO DO
> 
>     * Go and open **[README](https://github.com/BitByte-TPC/first-bit/blob/master/README.md)**.
> 
>     * Follow the steps there rocket tada.
> 
> 
> 
> ![Hacktoberfest2020](https://raw.githubusercontent.com/adityaarakeri/super-scripts/master/hacktoberfest2020.png)

**Comment by dikshantmali** [comment]
Hey @avats-dev I also want to contribute thanks for complete guide for how to make your first PR on github.

**Comment by MHFarooqui** [comment]
@avats-dev This is great!, would definitely submit a pr.
